import { stdin } from "../cli/stdin.ts"

/** Decrypts a token generated by {@link encrypt}. */
export async function decrypt(token: string): Promise<string> {
  function base64Decode(base64: string): Uint8Array {
    return Uint8Array.from(
      atob(base64.replace(/-/g, "+").replace(/_/g, "/")),
      (c) => c.charCodeAt(0),
    )
  }

  const [encodedEncryptedData, encodedPrivateKeyData] = token.split(".")

  const combined = base64Decode(encodedEncryptedData)
  const privateKeyBytes = base64Decode(encodedPrivateKeyData)
  const privateKeyBuffer = Uint8Array.from(privateKeyBytes)

  // Extract components from combined data
  const encryptedKey = combined.slice(0, 256) // First 256 bytes is RSA-encrypted AES key
  const iv = combined.slice(256, 272) // Next 16 bytes is AES IV
  const encryptedContent = combined.slice(272) // Rest is AES-encrypted content

  // Import RSA private key
  const rsaAlgorithm = { name: "RSA-OAEP", hash: "SHA-1" }
  const privateKey = await crypto.subtle.importKey(
    "pkcs8",
    privateKeyBuffer,
    rsaAlgorithm,
    false,
    ["decrypt"],
  )

  // Decrypt the AES key using RSA
  const aesKey = await crypto.subtle.decrypt(
    rsaAlgorithm,
    privateKey,
    encryptedKey,
  )

  // Import the AES key
  const aesKeyObj = await crypto.subtle.importKey(
    "raw",
    aesKey,
    { name: "AES-CBC", length: 256 },
    false,
    ["decrypt"],
  )

  // Decrypt the content using AES
  const decryptedContent = await crypto.subtle.decrypt(
    {
      name: "AES-CBC",
      iv: iv,
    },
    aesKeyObj,
    encryptedContent,
  )

  return new TextDecoder().decode(decryptedContent)
}

// echo "HelloWorld" | deno run crypto/encrypt.ts | bun crypto/decrypt.ts
// deno-coverage-ignore
if (import.meta.main) console.log(await decrypt(await stdin()))
