import { base64Decode } from "../encoding/base64Decode.ts"
import { stdin } from "../cli/stdin.ts"

const ENCRYPTED_KEY_LENGTH = 256
const IV_LENGTH = 16
const RSA_ALGORITHM = { name: "RSA-OAEP", hash: "SHA-1" } as const
const AES_ALGORITHM = { name: "AES-CBC", length: 256 } as const

type ParsedEncryptedToken = {
  encryptedContent: Uint8Array<ArrayBuffer>
  encryptedKey: Uint8Array<ArrayBuffer>
  iv: Uint8Array<ArrayBuffer>
  privateKeyBytes: Uint8Array<ArrayBuffer>
}

/** Deobfuscates a token generated by {@link obfuscate}. */
export async function deobfuscate(token: string): Promise<string> {
  const { encryptedContent, encryptedKey, iv, privateKeyBytes } = parseEncryptedToken(token)
  const privateKey = await importPrivateKeyPkcs8(privateKeyBytes)
  const aesKey = await decryptAesKey(privateKey, encryptedKey)
  const importedAesKey = await importAesKey(aesKey)
  const decryptedContent = await decryptWithAes(importedAesKey, iv, encryptedContent)

  return new TextDecoder().decode(decryptedContent)
}

function parseEncryptedToken(token: string): ParsedEncryptedToken {
  const parts = token.split(".")

  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new Error("Invalid token format")
  }

  const [encodedEncryptedData, encodedPrivateKeyData] = parts
  const combined = base64Decode(encodedEncryptedData)

  if (combined.length < ENCRYPTED_KEY_LENGTH + IV_LENGTH) {
    throw new Error("Invalid encrypted payload")
  }

  return {
    encryptedContent: copyBytes(combined.slice(ENCRYPTED_KEY_LENGTH + IV_LENGTH)),
    encryptedKey: copyBytes(combined.slice(0, ENCRYPTED_KEY_LENGTH)),
    iv: copyBytes(combined.slice(ENCRYPTED_KEY_LENGTH, ENCRYPTED_KEY_LENGTH + IV_LENGTH)),
    privateKeyBytes: copyBytes(base64Decode(encodedPrivateKeyData)),
  }
}

function copyBytes(bytes: Uint8Array): Uint8Array<ArrayBuffer> {
  const buffer = new ArrayBuffer(bytes.byteLength)
  const copy = new Uint8Array(buffer)
  copy.set(bytes)
  return copy
}

async function importPrivateKeyPkcs8(privateKeyBytes: Uint8Array<ArrayBuffer>) {
  return await crypto.subtle.importKey(
    "pkcs8",
    Uint8Array.from(privateKeyBytes),
    RSA_ALGORITHM,
    false,
    ["decrypt"],
  )
}

async function decryptAesKey(
  privateKey: CryptoKey,
  encryptedKey: Uint8Array<ArrayBuffer>,
) {
  return await crypto.subtle.decrypt(
    RSA_ALGORITHM,
    privateKey,
    encryptedKey,
  )
}

async function importAesKey(aesKey: ArrayBuffer) {
  return await crypto.subtle.importKey(
    "raw",
    aesKey,
    AES_ALGORITHM,
    false,
    ["decrypt"],
  )
}

async function decryptWithAes(
  aesKey: CryptoKey,
  iv: Uint8Array<ArrayBuffer>,
  encryptedContent: Uint8Array<ArrayBuffer>,
) {
  return await crypto.subtle.decrypt(
    {
      name: AES_ALGORITHM.name,
      iv,
    },
    aesKey,
    encryptedContent,
  )
}

// echo "HelloWorld" | deno run crypto/obfuscate.ts | bun crypto/deobfuscate.ts
// deno-coverage-ignore
if (import.meta.main) console.log(await deobfuscate(await stdin()))
