import { base64Decode } from "../encoding/base64Decode.ts"
import { stdin } from "../cli/stdin.ts"

const TEXT_DECODER = new TextDecoder()
const ENCRYPTED_KEY_LENGTH = 256
const IV_LENGTH = 16
const RSA_ALGORITHM = { name: "RSA-OAEP", hash: "SHA-1" } as const
const AES_ALGORITHM = { name: "AES-CBC", length: 256 } as const

type ParsedEncryptedToken = {
  encryptedContent: Uint8Array<ArrayBuffer>
  encryptedKey: Uint8Array<ArrayBuffer>
  iv: Uint8Array<ArrayBuffer>
  privateKeyBytes?: Uint8Array<ArrayBuffer>
}

/** Deobfuscates a token generated by {@link obfuscate}. */
export async function deobfuscate(
  token: string,
  privateKey: CryptoKey | string | Uint8Array<ArrayBuffer> | ArrayBuffer | undefined = undefined,
): Promise<string> {
  const { encryptedContent, encryptedKey, iv, privateKeyBytes } = parseEncryptedToken(token)
  const importedPrivateKey = await resolvePrivateKey(privateKey, privateKeyBytes)
  const aesKey = await decryptAesKey(importedPrivateKey, encryptedKey)
  const importedAesKey = await importAesKey(aesKey)
  const decryptedContent = await decryptWithAes(importedAesKey, iv, encryptedContent)

  return TEXT_DECODER.decode(decryptedContent)
}

function parseEncryptedToken(token: string): ParsedEncryptedToken {
  const parts = token.split(".")

  if (parts.length > 2 || !parts[0]) {
    throw new Error("Invalid token format")
  }

  const [encodedEncryptedData, encodedPrivateKeyData] = parts
  let combined: Uint8Array

  try {
    combined = base64Decode(encodedEncryptedData)
  } catch {
    throw new Error("Invalid token format")
  }

  if (combined.length < ENCRYPTED_KEY_LENGTH + IV_LENGTH) {
    throw new Error("Invalid encrypted payload")
  }

  return {
    encryptedContent: copyBytes(combined.slice(ENCRYPTED_KEY_LENGTH + IV_LENGTH)),
    encryptedKey: copyBytes(combined.slice(0, ENCRYPTED_KEY_LENGTH)),
    iv: copyBytes(combined.slice(ENCRYPTED_KEY_LENGTH, ENCRYPTED_KEY_LENGTH + IV_LENGTH)),
    privateKeyBytes: encodedPrivateKeyData ? copyBytes(base64Decode(encodedPrivateKeyData)) : undefined,
  }
}

function copyBytes(bytes: Uint8Array): Uint8Array<ArrayBuffer> {
  const buffer = new ArrayBuffer(bytes.byteLength)
  const copy = new Uint8Array(buffer)
  copy.set(bytes)
  return copy
}

async function importPrivateKeyPkcs8(privateKeyBytes: Uint8Array<ArrayBuffer>) {
  return await crypto.subtle.importKey(
    "pkcs8",
    Uint8Array.from(privateKeyBytes),
    RSA_ALGORITHM,
    false,
    ["decrypt"],
  )
}

async function resolvePrivateKey(
  privateKey:
    | ArrayBuffer
    | CryptoKey
    | Uint8Array<ArrayBuffer>
    | string
    | undefined,
  privateKeyBytes?: Uint8Array<ArrayBuffer>,
) {
  if (privateKey instanceof CryptoKey) {
    return privateKey
  }

  if (typeof privateKey === "string") {
    return await importPrivateKeyPkcs8(copyBytes(base64Decode(privateKey)))
  }

  if (privateKey instanceof ArrayBuffer) {
    return await importPrivateKeyPkcs8(new Uint8Array(privateKey))
  }

  if (privateKey instanceof Uint8Array) {
    return await importPrivateKeyPkcs8(privateKey)
  }

  if (!privateKeyBytes) {
    throw new Error("Missing private key")
  }

  return await importPrivateKeyPkcs8(privateKeyBytes)
}

async function decryptAesKey(
  privateKey: CryptoKey,
  encryptedKey: Uint8Array<ArrayBuffer>,
) {
  return await crypto.subtle.decrypt(
    RSA_ALGORITHM,
    privateKey,
    encryptedKey,
  )
}

async function importAesKey(aesKey: ArrayBuffer) {
  return await crypto.subtle.importKey(
    "raw",
    aesKey,
    AES_ALGORITHM,
    false,
    ["decrypt"],
  )
}

async function decryptWithAes(
  aesKey: CryptoKey,
  iv: Uint8Array<ArrayBuffer>,
  encryptedContent: Uint8Array<ArrayBuffer>,
) {
  return await crypto.subtle.decrypt(
    {
      name: AES_ALGORITHM.name,
      iv,
    },
    aesKey,
    encryptedContent,
  )
}

// echo "HelloWorld" | deno run crypto/obfuscate.ts | bun crypto/deobfuscate.ts
// deno-coverage-ignore
if (import.meta.main) console.log(await deobfuscate(await stdin()))
